### ISSUE TITLE
LCD flickering

### ISSUE THREAD

**Issue by abdollahpour** [kanflo/commadorable-64#1]
First of all, I want to say thanks for the great project shared.
It works well, I just have one annoying issue that I can not solve. The LCD flickers so much when I use USB power from my Laptop, it's much better with direct charger. Is there any way to fix it?

**Comment by kanflo** [comment]
Thanks! I don't think it's possible to power the Commadoreble 64 from a computer USB port. A normal USB 2.0 device can only draw 100mA until it enumerates itself as a high power device after which it may draw 500mA (IIRC). As the Commadorable 64 is no USB device per se, its limited to 100mA which probably is too little.

**Comment by abdollahpour** [comment]
Understood, thanks
